name: PHPCS check

on:
  pull_request:
    branches:
      - master
      - development
      - sovware:master
      - sovware:development

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          ini-values: 'memory_limit=1G'
          coverage: none
          tools: cs2pr

      - name: Install Composer dependencies
        run: composer setup

      - name: Run PHPCS checks
        run: composer phpcs

      - name: Show PHPCS results in PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          COMMENT="PHPCS results:\n\`\`\`\n$(cat ./phpcs-report.xml)\n\`\`\`"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          API_URL=$(jq -r .repository.issue_comment_url $GITHUB_EVENT_PATH | sed 's/{.*}//')
          curl -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -X POST -d "{\"body\":\"$COMMENT\"}" "$API_URL"
